### ISSUE TITLE
Hardware Not Found

### ISSUE THREAD

**Issue by waltz** [cwhitney/GoldsprintsFx#12]
Hey all! I'm having some trouble getting things going. I have an OpenSprints box that I bought from a friend-of-a-friend. It seems to work alright. I downloaded the latest release and uploaded the latest Arduino code.

When I start SilverSprint, the 'Hardware Connection Status' always shows an 'X'. It doesn't seem to find the hardware. If I run SilverSprint from the command line, I see this:

`|info   | void gfx::SerialReader::updateSerialThread()[104] OpenSprints hardware found successfully. :: /dev/cu.usbserial-A7005O0S`

Which suggests that SilverSprint is kinda sorta able to find my box.

If I connect to that serial device, I can send commands to the OpenSprints hardware and get back a stream of timestamps and results. The hardware seems to respond how I would expect.

Any idea what's going on here?

This is an older SilverSprint box, probably pre-2012. Are there issues with cloned Arduinos?

**Comment by jonfen** [comment]
[Arduino Uno rev3](https://store.arduino.cc/usa/arduino-uno-rev3) is what you need.  Use these [instructions](https://www.opensprints.com/howto_hub_assembly.php) to take it apart.

But if you are interested in the specific tests, see my other [issue comments](https://github.com/cwhitney/SilverSprint/issues/7)

**Comment by waltz** [comment]
I busted open the box to check which Arduino I have, it turns out to be a Duemilanove. It looks  authentic with a giant 'Made in Italy' graphic.

What's the technical reason that these don't work? It seems talk over the serial port just fine. My Ruby script reads data from it but SilverSprint doesn't.

**Comment by jonfen** [comment]
The issue isn't clones, it is FTDI chips, which Arduino did away with on the Uno.  If you don't want to spend the $30 you can try installing [GoldSprintsFX](https://www.opensprints.com/howto_install_goldsprintsfx.php).  But again, driver issues with the FTDI chipsets (clone or not) aren't fun.

**Comment by waltz** [comment]
Thanks for suggesting that I switch to the new Uno R3. I bought one and installed it. The software and hardware worked flawlessly for an event I did this weekend.

**Comment by jonfen** [comment]
@cwhitney if your software detects anything besides the Uno R3, can you pop up a message saying buy an Arduino Uno Rev3?

**Comment by cwhitney** [comment]
@jonfen I can't specifically detect if they have an alternate version, but in an upcoming version I'm going to expose a dropdown list of serial devices they can choose from, which should potentially be able to include clones.  We can put up some recommended specs though.
