### ISSUE TITLE
Come up with a good name

### ISSUE THREAD

**Issue by cwhitney** [cwhitney/GoldsprintsFx#2]

**Comment by cwhitney** [comment]
Initial braindump:

**Superelevation** - From the way tracks bank on a veladrome (http://en.wikipedia.org/wiki/Cant_(road/rail))
**FreeRide** - For the biking connotation, plus it's free software
**Massimo** - For Circo Massimo aka the Circus Maximus, the ancient Roman racing track. (http://en.wikipedia.org/wiki/Circus_Maximus)
**GrannyGear** - Ha.
**Peloton** - Something with this is the name.  I just like the word, although it's use is pretty played out in cycling. (http://en.wikipedia.org/wiki/Peloton)

All kind of esoteric, and douchy, but hey.

**Comment by jonfen** [comment]
It would be great to keep GoldSprints and or Roller Racing in the title, just for the sake of natural SEO, but I do love a creative name.

HammerDrop
HellHammer
TurkeySmoke
DrumCycle
PedalCircus - Blood, Sweat and Beers.

I like one word titles, Massimo is good that way.

**Comment by cwhitney** [comment]
Current working title is now SilverSprint.  We can still utilize goldsprints somewhere in a subhead or whatever for SEO.

**Comment by ehusar** [comment]
Sounds great. When will you change the name on Github?

**Comment by cwhitney** [comment]
Knew I was forgetting something :)
