### ISSUE TITLE
Text and buttons are misaligned on Riders and Settings screens

### ISSUE THREAD

**Issue by alexrotaru** [cwhitney/GoldsprintsFx#27]
I opened version 0.1.7.1 64bit on a Windows 10 64 bit with a screen resolution of 3200 x 1800.
I opened the screens of the application and noticed that the buttons and the text are not aligned. 

![SilverSprint_Riders](https://user-images.githubusercontent.com/3822903/55306867-633b4b00-545e-11e9-9726-b78e574e2d0c.png)
![SilverSprint_Settings](https://user-images.githubusercontent.com/3822903/55306869-633b4b00-545e-11e9-888f-ba87758864e2.png)

I opened the application on another laptop with screen resolution of1920 x 1080, and the text and buttons looked almost perfect. (only the timer from the main screen is a bit off)

**Comment by cwhitney** [comment]
Thanks for this. I can confirm that on screens with larger resolutions I can replicate. Fix on the way.

**Comment by alexrotaru** [comment]
thanks a lot! if you need any help with testing the issue, please let me know.

**Comment by cwhitney** [comment]
This was fixed in version 0.1.8
