### ISSUE TITLE
Logging of race data

### ISSUE THREAD

**Issue by cwhitney** [cwhitney/GoldsprintsFx#8]
Users should have the option of automatically logging race data.

It would likely be in a csv format that could be imported into spreadsheets.  To keep it sane, it would create one csv per day, and log each race into the same file.  For four racers, it would add four entries, for two racers, it would add two entries, etc.

__YYYY_MM_DD_Racedata.csv__
`race_start_time, player_name, finish_time, max_speed_kmh`

Other optional fields could be `max_speed_mph, finish_place, num_racers_in_race`

**Comment by jonfen** [comment]
@cwhitney does it also make sense to ID the race, that way we can query to see who raced against who too?

**Comment by cwhitney** [comment]
@jonfen All racers in the same race would all have the same `race_start_time` though it would be easy enough to also add a more human-readable `race_id`

**Comment by cwhitney** [comment]
A basic implementation is in as of v0.1.5.  Now that it's in it will be easier to refine what exactly it logs.

Currently the log will show:
`timestamp - event type (time, distance) - racer 1 - racer 2 - racer 3 - racer 4`

This makes it easier to manipulate with a spreadsheet when they are all on the same line.
