### ISSUE TITLE
Compiling (on Linux) missing 'app/GFXMain.h'

### ISSUE THREAD

**Issue by jonfen** [cwhitney/GoldsprintsFx#9]
It doesn't look like any of the header files are checked in.

$ make
Scanning dependencies of target SilverSprintApp
[ 50%] Building CXX object CMakeFiles/SilverSprintApp.dir/home/jonfen/dev/github.com/cinder/Cinder/samples/SilverSprint/src/SilverSprintApp.cpp.o
/home/jonfen/dev/github.com/cinder/Cinder/samples/SilverSprint/src/SilverSprintApp.cpp:5:10: fatal error: 'app/GFXMain.h' file not
      found
#include "app/GFXMain.h"

**Comment by cwhitney** [comment]
They are all checked in in the "includes" folder.  You'll need to add "/include" to your header include path.  You shouldn't have to add the subfolders.
